# Baseline Configuration for WhisperLive Optimization Testing - 2 Connections Only
# This represents the default/reference configuration with explicit 2 connections

server:
  ws_url: "ws://localhost:9090/ws"  # For local testing
  language: "en"
  model: "medium"

run:
  concurrency: 2                  # EXPLICITLY set to 2 connections
  frame_ms: 20                    # Audio frame size in milliseconds
  warmup_s: 2                     # Warmup duration in seconds
  run_s: 5                        # Main test duration in seconds (very short for testing)
  cooldown_s: 2                   # Cooldown duration in seconds
  repeat_audio: true              # Repeat audio samples if needed
  shuffle_audio: true             # Shuffle audio sample order
  per_conn_seed: true             # Use fixed seed for reproducibility

data:
  manifest: "data/manifest.csv"   # Path to audio manifest file

metrics:
  lambda: 0.5                     # Penalty weight for standard deviation
  latency_slo: 2.0               # Latency SLO threshold in seconds
  drop_slo: 0.02                 # Drop rate SLO threshold (2%)
  gpu_sample_s: 1.0              # GPU metrics sampling interval

quality:
  enable_simple: true             # Enable simple text quality metrics
  enable_llm: false              # Enable LLM judge assessment

# Advanced settings
advanced:
  max_concurrent_connections: 1000  # Max concurrent client connections
  connection_jitter_ms: 100       # Jitter between connection starts (ms)
  metrics_sample_rate: 1.0        # Metrics sampling rate (Hz)
  steady_state_window: 20         # Steady state detection window (seconds)
  steady_state_threshold: 0.03    # Steady state threshold (3% change)
